"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                 CROP DISEASE DETECTOR    CLI Prediction Script               ║
║                                                                              ║
║  Usage:                                                                      ║
║    python predict.py <path_to_image>                                         ║
║    python predict.py <path_to_image> <optional_model_path>                   ║
║                                                                              ║
║  Requirements:                                                               ║
║    • model_best.pth  (generated by train.py)                                 ║
║    • class_names.json (auto-generated by train.py)                           ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
import sys
import json
import os

# ══════════════════════════════════════════════════════════════════════════════
#  CONFIG  ←  Adjust thresholds if needed
# ══════════════════════════════════════════════════════════════════════════════
CONFIDENCE_THRESHOLD = 0.85   # Raised to extremely strict levels (85%)
ENTROPY_THRESHOLD    = 1.50   # Max allowed entropy (higher = more uncertain)
USE_CLIP_GUARD       = True   # Set False to skip CLIP check (faster)

NON_PLANT_PROMPTS = [
    "a photo of a car",
    "a photo of a person",
    "a photo of a building",
    "a photo of an animal",
    "a photo of food",
    "a photo of random objects",
    "a photo of a person's hand",
    "an indoor room scene",
    "a digital screenshot or text",
    "random color texture or noise",
    "a blurry or irrelevant image",
]
CLIP_PLANT_THRESHOLD = 0.40   # CLIP must assign ≥40% probability to plant prompts
# ══════════════════════════════════════════════════════════════════════════════


# ── Device ────────────────────────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ── Load class names ──────────────────────────────────────────────────────────
try:
    with open("class_names.json", "r") as f:
        CLASSES = json.load(f)
except FileNotFoundError:
    print("❌  Error: 'class_names.json' not found.")
    print("   Run  train.py  first to generate the model and class list.")
    sys.exit(1)

# Dynamic CLIP Prompts based on the trained crop
PLANT_PROMPTS = [
    f"a photo of a {c.replace('_', ' ')} leaf" 
    for c in CLASSES if c.lower() != "background"
] + [
    "a close-up of agricultural foliage",
    "a photo of a crop leaf with disease",
    "a photo of a healthy plant leaf"
]

# ── CLIP guard ────────────────────────────────────────────────────────────────
def load_clip_model():
    """Lazy-load CLIP. Falls back gracefully if not installed."""
    try:
        import clip
        model, preprocess = clip.load("ViT-B/32", device=device)
        return model, preprocess
    except ImportError:
        print("⚠️  CLIP not installed. Falling back to confidence/entropy guard only.")
        print("    To enable: pip install git+https://github.com/openai/CLIP.git\n")
        return None, None


def is_plant_image_clip(pil_image, clip_model, clip_preprocess) -> tuple[bool, float]:
    """Uses zero-shot CLIP to check if the image contains plant/leaf content."""
    import clip
    all_prompts  = PLANT_PROMPTS + NON_PLANT_PROMPTS
    text_tokens  = clip.tokenize(all_prompts).to(device)
    image_tensor = clip_preprocess(pil_image).unsqueeze(0).to(device)

    with torch.no_grad():
        img_feat  = clip_model.encode_image(image_tensor)
        text_feat = clip_model.encode_text(text_tokens)
        img_feat  = img_feat  / img_feat.norm(dim=-1, keepdim=True)
        text_feat = text_feat / text_feat.norm(dim=-1, keepdim=True)
        probs = (img_feat @ text_feat.T).squeeze(0).softmax(dim=0).cpu()

    plant_score = probs[: len(PLANT_PROMPTS)].sum().item()
    return plant_score >= CLIP_PLANT_THRESHOLD, plant_score


# ── Disease classifier ─────────────────────────────────────────────────────────
def load_disease_model(model_path: str):
    """Loads the trained ResNet-18 model."""
    model = models.resnet50(weights=None)
    model.fc = nn.Sequential(
        nn.Dropout(0.4),
        nn.Linear(model.fc.in_features, len(CLASSES)),
    )
    model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
    return model.to(device).eval()


transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])


def predict_disease(pil_image, disease_model) -> dict:
    """Run the disease classifier and return a results dict."""
    tensor = transform(pil_image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs       = disease_model(tensor)
        probabilities = torch.softmax(outputs, dim=1).squeeze(0)
        confidence, predicted_idx = probabilities.max(0)

    entropy = -(probabilities * (probabilities + 1e-9).log()).sum().item()
    predicted_class = CLASSES[predicted_idx.item()]

    # If it predicts the "Background" class, override the class name to be clear
    if predicted_class.lower() == "background":
        status_label = "Background / Non-Leaf"
    else:
        status_label = predicted_class
    
    return {
        "class":      status_label,
        "confidence": confidence.item(),
        "entropy":    entropy,
        "all_probs":  {c: round(p.item(), 4) for c, p in zip(CLASSES, probabilities)},
    }


# ── Main pipeline ──────────────────────────────────────────────────────────────
def classify(image_path: str, model_path: str = "model_best.pth") -> None:
    print(f"\n📂 Image  : {image_path}")
    print(f"🧩 Model  : {model_path}")
    print("─" * 55)

    # Load image
    try:
        pil_image = Image.open(image_path).convert("RGB")
    except Exception as e:
        print(f"❌  Could not open image: {e}")
        return

    # GATE 1: CLIP semantic guard
    if USE_CLIP_GUARD:
        print("🔍 Running CLIP plant/leaf check …")
        clip_model, clip_preprocess = load_clip_model()

        if clip_model is not None:
            is_plant, plant_score = is_plant_image_clip(pil_image, clip_model, clip_preprocess)
            print(f"   Plant score : {plant_score*100:.1f}%  (threshold ≥ {CLIP_PLANT_THRESHOLD*100:.0f}%)")

            if not is_plant:
                print(f"\n🚫 REJECTED — Image does not appear to be crop foliage.")
                print(f"   Please provide a clear close-up photo of a leaf.")
                return
            print("   ✅ Looks like a plant. Proceeding …\n")

    # Load disease model
    if not os.path.exists(model_path):
        print(f"\n❌  MODEL NOT FOUND: '{model_path}'")
        print("─" * 55)
        print("📥  It looks like you haven't trained your model yet!")
        print("👉  To fix this, please run:")
        print("    python train.py")
        print("─" * 55)
        return

    # Run classifier
    result = predict_disease(pil_image, disease_model)

    if result["class"] == "Background / Non-Leaf":
        print(f"\n🚫 REJECTED — Image classified as 'Background / Non-Leaf'.")
        print("   The model learned to ignore images like this.")
        return

    # GATE 2: Confidence + Entropy check
    low_confidence = result["confidence"] < CONFIDENCE_THRESHOLD
    high_entropy   = result["entropy"]    > ENTROPY_THRESHOLD

    print(f"   Predicted   : {result['class']}")
    print(f"   Confidence  : {result['confidence']*100:.2f}%  (min: {CONFIDENCE_THRESHOLD*100:.0f}%)")
    print(f"   Entropy     : {result['entropy']:.3f}          (max: {ENTROPY_THRESHOLD:.2f})")

    if low_confidence or high_entropy:
        reasons = []
        if low_confidence:
            reasons.append(f"confidence too low ({result['confidence']*100:.1f}%)")
        if high_entropy:
            reasons.append(f"prediction too uncertain (entropy {result['entropy']:.2f})")
        print(f"\n⚠️  UNCERTAIN — {' and '.join(reasons)}.")
        print("   The image may not match any trained category clearly.")
        return

    # All gates passed — show result
    label = result["class"].replace("_", " ")
    print(f"\n✅ Prediction  : {label}")
    print(f"   Confidence  : {result['confidence']*100:.2f}%")


    # Top-3 alternatives
    sorted_probs = sorted(result["all_probs"].items(), key=lambda x: x[1], reverse=True)
    print("\n📊 Top-3 probabilities:")
    for cls, prob in sorted_probs[:3]:
        bar = "█" * int(prob * 30)
        print(f"   {cls:<45} {prob*100:5.1f}%  {bar}")


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python predict.py <path_to_image> [optional_model_path]")
        sys.exit(1)

    image_path = sys.argv[1]
    model_path = sys.argv[2] if len(sys.argv) > 2 else "model_best.pth"
    classify(image_path, model_path=model_path)